# fly.toml app configuration file generated for bin-bot on 2025-02-20T22:18:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bin-bot'
primary_region = 'lhr'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[build]
  dockerfile = "Dockerfile"
